name = "ethernet_io"
version = "0.1.0"
[dependencies]
jsl = { path = "libs/jsl"}
connectors = { path = "libs/connectors"}
voltage-divider = { path = "libs/voltage-divider" }
power-systems = { path = "libs/power-systems"}
ethernet_io_lib = { path = "libs/ethernet_io_lib"}
inductors = { path = "libs/inductors" }
jlc-pcb = {path = "libs/jlc-pcb"}
stmicro = {path = "libs/stmicro"}
TI-vreg = { path = "libs/TI-VREG" }
microchip-networking = { path = "libs/microchip-networking"}
JITX = { path = "{SLM_ROOT}/JITX" }
ocdb = { path = "{SLM_ROOT}/ocdb" }
