name = "ethernet_io"
version = "0.1.0"
[dependencies]
jsl = { path = "libs/jsl"}
connectors = { path = "libs/connectors"}
power-systems = { path = "libs/power-systems"}
ethernet_io_lib = { path = "libs/ethernet_io_lib"}
jlc-pcb = {path = "libs/jlc-pcb"}
stmicro = {path = "libs/stmicro"}
JITX = { path = "{SLM_ROOT}/JITX" }
ocdb = { path = "{SLM_ROOT}/ocdb" }
