name = "ethernet_io"
version = "0.1.0"
[dependencies]
jsl = { git = "JITx-Inc/jsl", version = "0.4.0" }
#jsl = { path = "{HOME}/src/jsl"}
ethernet_io_lib = { git = "JITx-Inc/ethernet_io_lib", version="0.1.0"}
# ethernet_io_lib = { path = "{HOME}/designs/ethernet_io_lib"}
JITX = { path = "{SLM_ROOT}/JITX" }
ocdb = { path = "{SLM_ROOT}/ocdb" }
